# nixpacks.toml

[phases.setup]

nixPkgs = [
  "python313"
]

aptPkgs = [
  "build-essential",
  "libffi-dev",
  "shared-mime-info",
  "libjpeg-dev",
  "zlib1g-dev",
  "libfreetype6-dev",
  "liblcms2-dev",
  "libtiff5-dev",
  "libwebp-dev"
]

[phases.python_install]
dependsOn = ['setup']
cmds = ['pip install -r requirements.txt']

[phases.build]
# Colectar archivos estáticos y migrar la base de datos
cmds = ["python manage.py collectstatic --noinput", "python manage.py migrate"]

[start]
# Comando para iniciar la aplicación
cmd = "gunicorn --timeout 240 Fieldex.wsgi"
